language: node_js
node_js:
    - "node"
cache: npm
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: out
    repo: sarthakmittal777/jan24
    target_branch: gh-pages
    on:
       branch: main
